blogs/urls.py
from django.urls import path

from .views import (
    BlogList, BlogDetail, BlogListAPI, BlogRetrieveAPI,
)

app_name = 'blogs'
urlpatterns = [
    path('', BlogList.as_view(), name='index'),
    path('<slug:slug>/', BlogDetail.as_view(), name='detail'),
    path('api/posts/', BlogListAPI.as_view(), name='api_index'),
    path('api/posts/<slug:slug>/', BlogRetrieveAPI.as_view(), name='api_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class Author(AbstractUser):
    pass


class Blog(models.Model):
    title = models.CharField('タイトル', max_length=150)
    slug = models.SlugField('スラッグ', unique=True)
    text = models.TextField('本文', blank=True)
    created_datetime = models.DateTimeField('作成日', auto_now_add=True)
    updated_datetime = models.DateTimeField('更新日', auto_now=True)

    class Meta:
        ordering = ('-created_datetime',)

    def __str__(self):
        return self.title

blogs/forms.py
from django import forms
from django.db.models import Q

from .models import Blog


class BlogSearchForm(forms.Form):
    keyword = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={
            'class': 'form-control mr-sm-2',
            'placeholder': '記事を検索'
        }),
        required=False,
    )

    def filter_blogs(self, blogs):
        if self.is_valid():
            keyword = self.cleaned_data.get('keyword')
            if keyword:
                blogs = blogs.filter(
                    Q(title__icontains=keyword) | Q(text__icontains=keyword)
                )

        return blogs

blogs/views.py
from django.views.generic import (
    ListView, DetailView,
)
from rest_framework.generics import (
    ListAPIView, RetrieveAPIView,
)

from .forms import BlogSearchForm
from .models import Blog
from .serializers import (
    BlogListSerializer, BlogRetrieveSerializer,
)


# Create your views here.

class BlogList(ListView):
    model = Blog
    template_name = 'blogs/index.html'
    paginate_by = 10

    def get_queryset(self):
        form = BlogSearchForm(self.request.GET)
        queryset = super().get_queryset()
        queryset = form.filter_blogs(queryset)
        return queryset

    def get_context_data(self):
        context = super().get_context_data()
        context['search_form'] = BlogSearchForm(self.request.GET)
        return context


class BlogDetail(DetailView):
    model = Blog
    template_name = 'blogs/detail.html'


class BlogListAPI(ListAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogListSerializer


class BlogRetrieveAPI(RetrieveAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogRetrieveSerializer
    lookup_field = 'slug'

templates/blogs/detail.html
<!DOCTYPE html>

<html lang="ja">

{% load static %}



  <head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% bootstrap_css %}

    <title>ブログアプリ</title>


  </head>



  <body>


    <h1 class="text-center my-5">{{ blog.title }}</h1>

    <div class="container mx-auto">
      <div>
        <div class="mx-3 my-5">
          {{ blog.text | linebreaksbr | urlize }}
        </div>
        <div class="text-center mt-5">
          <a href="{% url 'blogs:index' %}">トップページに戻る</a>
        </div>
      </div>
    </div>

    {% bootstrap_javascript jquery='full' %}


  </body>



</html>

templates/blogs/includes/paginator.html
{% load blogs_tags %}

<nav aria-label="Page navigation" class="my-5">

  <ul class="pagination justify-content-center">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    
  </ul>

</nav>

templates/blogs/index.html
<!DOCTYPE html>

<html lang="ja">

{% load static %}



  <head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ブログ管理サイト</title>
    
    {% bootstrap_css %}


  </head>



  <body>


    <h1 class="text-center my-5"><a href="{% url 'blogs:index' %}" class="text-dark">My Blog</a></h1>

    <div class="container mx-auto">

      <form action="" class="form-inline">

        {% if search_form.non_field_errors %}
        <div class="error-list text-danger font-weight-bold">
          {% for error in search_form.non_field_errors %}
            {{ error }}
          {% endfor %}
        </div>
        {% endif %}

        {% for field in search_form %}
        <div class="form-group">
          {{ field.label_tag }}
          {{ field }}
          {% if field.errors %}
          <div class="error-list text-danger font-weight-bold">
            {% for error in field.errors %}
              {{ error }}
            {% endfor %}
          </div>
          {% endif %}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-outline-primary">検索</button>
        
      </form>

      <hr />

      {% for blog in blog_list %}
      <div>
        <h3>{{ blog.title }}</h3>
        <div>{{ blog.text | truncatechars:100 }}</div>
        <div style="text-align: right;">
          <a href="{% url 'blogs:detail' slug=blog.slug %}">記事を読む</a>
        </div>
      </div>
      <hr />
      {% empty %}
      <p>表示する記事がありません。</p>
      <hr />
      {% endfor %}

      {% include 'blogs/includes/paginator.html' %}
      
    </div>

    {% bootstrap_javascript jquery='full' %}


  </body>

</html>